miniorange_oauth_client.settings:
  type: mapping
  label: Settings
  mapping:
    miniorange_oauth_client_customer_admin_email:
      type: 'NULL'
    miniorange_oauth_client_customer_id:
      type: string
    miniorange_oauth_client_customer_admin_token:
      type: string
    miniorange_oauth_client_customer_api_key:
      type: string
    miniorange_oauth_client_email_attr_val:
      type: string
    miniorange_oauth_client_username_attribute:
      type: string
    miniorange_oauth_client_email_attribute:
      type: string
    miniorange_oauth_client_status:
      type: string
    miniorange_oauth_client_tx_id:
      type: 'NULL'
    miniorange_oauth_client_customer_admin_password:
      type: string
    miniorange_oauth_client_base_url :
      type: string  
    miniorange_oauth_enable_login_with_oauth:
      type: boolean
    miniorange_oauth_send_with_header_oauth:
      type: boolean
    miniorange_oauth_send_with_body_oauth:
      type: boolean
    miniorange_auth_client_display_name:
      type: string
    miniorange_auth_client_test_configuration_status:
      type: string
    miniorange_auth_client_sso_status:
      type: string
    miniorange_auth_client_access_token_status:
      type: string
    miniorange_auth_client_userinfo_status:
      type: string