choices_autocomplete:
  type: mapping
  mapping:
    options:
      type: mapping
      label: 'Options'
      mapping:
        instance:
          type: mapping
          label: 'Instance'
          mapping:
            remove_item_text:
              type: label
              label: 'Remove item text'
            none_text:
              type: label
              label: 'No selection text'
        plugin:
          type: mapping
          label: 'Plugin'
          mapping:
            searchPlaceholderValue:
              type: label
              label: 'Start typing text'
            loadingText:
              type: label
              label: 'Searching text'
            noResultsText:
              type: label
              label: 'No results text'
            itemSelectText:
              type: label
              label: 'Item select text'
            maxItemText:
              type: label
              label: 'Max items text'
            position:
              type: string
              label: 'Dropdown position'

field.widget.settings.options_select_choices:
  type: mapping

field.widget.settings.entity_reference_choices:
  type: mapping
  mapping:
    options:
      type: mapping
      mapping:
        instance:
          type: mapping
          mapping:
            input_type:
              type: string
              label: 'Limit characters'
            allowed_characters:
              type: string
              label: 'Allowed characters'
            minlength:
              type: integer
              label: 'Minimum length'
            maxlength:
              type: integer
              label: 'Maximum length'
